[package]
name = "sanuli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.19.3"
serde_scan = "0.4.1"
rand = "0.8.4"
getrandom = { version = "0.2", features = ["js"] }
